name: 'Tektor - Tekton Resource Validator'
description: 'Validate Tekton resources (Pipelines, Tasks, PipelineRuns) in pull requests using Tektor'
author: 'Tektor Team'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  files:
    description: 'Comma-separated list of files to validate. If not provided, will detect changed files automatically'
    required: false
    default: ''
  
  file-patterns:
    description: 'File patterns to match for Tekton resources (YAML/JSON files)'
    required: false
    default: '**/*.yaml,**/*.yml,**/*.json'
  
  exclude-patterns:
    description: 'File patterns to exclude from validation'
    required: false
    default: '.github/**,docs/**,README.md,**/README.md'
  
  fail-on-error:
    description: 'Whether to fail the action if validation errors are found'
    required: false
    default: 'true'
  
  verbose:
    description: 'Enable verbose logging output'
    required: false
    default: 'false'
  
  parameters:
    description: 'Runtime parameters for validation in key=value format, one per line'
    required: false
    default: ''
  
  detect-tekton-files:
    description: 'Auto-detect Tekton resource files by content (apiVersion: tekton.dev)'
    required: false
    default: 'true'

  changed-files-only:
    description: 'Only validate files that have changed in the PR (requires pull_request event)'
    required: false
    default: 'true'
  
  tektor-args:
    description: 'Additional arguments to pass to tektor command (e.g., "--param key=value --verbose")'
    required: false
    default: ''

outputs:
  validated-files:
    description: 'List of files that were validated'
  
  validation-results:
    description: 'Summary of validation results'
  
  error-count:
    description: 'Number of validation errors found'
  
  warning-count:
    description: 'Number of validation warnings found'

runs:
  using: 'docker'
  image: 'docker://quay.io/scoheb/tektor-action:latest' 
